variable "project" {
  description = "Path segment under the prefix, e.g. dfe."
  type        = string
}

variable "env" {
  description = "Path segment under the project, e.g. test."
  type        = string
}

variable "prefix" {
  description = "The deployment dial's secrets.ref. First path segment, and the boundary ESO's read grant is fenced to. OPTIONAL: empty leaves the deployment's own <project>/<env> path with nothing above it, which is what a store holding one deployment wants."
  type        = string
  default     = ""

  validation {
    condition     = !startswith(var.prefix, "/") && !endswith(var.prefix, "/")
    error_message = "prefix is a path segment with no leading or trailing slash. Leave it empty for a path of <project>/<env>."
  }
}

variable "seeds" {
  description = "Secret name -> field -> value. An empty value means generate one here, so the credential lands in the store without passing through a tfvars file or a plan output."
  type        = map(map(string))

  validation {
    condition     = alltrue([for name in keys(var.seeds) : !startswith(name, "/") && !endswith(name, "/")])
    error_message = "A seed name is a path under the prefix, with no leading or trailing slash."
  }

  validation {
    condition     = alltrue([for fields in var.seeds : length(fields) > 0])
    error_message = "A seed with no fields creates an empty secret nothing can read."
  }
}

variable "kafka_password" {
  description = "The Kafka user's SCRAM password, generated by the caller. It fills the password field of the kafka/<provider> seed, which this module never generates: a managed broker is CREATED with that value, so one minted in here could not match it. Null is for a deployment whose seeds carry no kafka entry."
  type        = string
  sensitive   = true
  default     = null

  validation {
    // Whether a value was supplied cannot be read at plan time -- it is not
    // known until apply -- so the seeds are what this checks.
    condition     = var.kafka_password != null || length([for name in keys(var.seeds) : name if startswith(name, "kafka/")]) == 0
    error_message = "seeds carry a kafka entry, so kafka_password has to be supplied: the broker is created with that password and cannot be handed one generated here."
  }
}

variable "recovery_window_days" {
  description = "Secrets Manager's deletion delay. Defaults to the vendor's own 30 days; the caller sets this from the dial's tags.lifecycle, passing 0 explicitly for an ephemeral deployment torn down and rebuilt under the same names, where the 30-day default would make the second create fail on a name that still exists."
  type        = number
  default     = 30

  validation {
    condition     = var.recovery_window_days == 0 || (var.recovery_window_days >= 7 && var.recovery_window_days <= 30)
    error_message = "recovery_window_days must be 0 (immediate) or between 7 and 30 -- Secrets Manager's own range."
  }
}

variable "kms_key_arn" {
  description = "The deployment's customer-managed key, from the cluster module. Every secret here is encrypted with it, and ESO is granted decrypt on it and nothing else."
  type        = string
}

variable "cluster_name" {
  description = "The EKS cluster whose external-secrets service account gets the identity."
  type        = string
}

variable "pod_identity_trust_policy_json" {
  description = "From the cluster module, so this module mints a role without restating how EKS expresses cluster trust."
  type        = string
}

variable "permissions_boundary" {
  description = "IAM policy ARN set as the permissions boundary on every role this module creates, or null for none."
  type        = string
  default     = null
}

variable "iam_path" {
  description = "IAM path for every role this module creates, or null for the default \"/\"."
  type        = string
  default     = null
}
