apiVersion: v2
name: dfe-transform-splack
description: "Splunk format conversion transform — Kafka consumer → Splunk format → Kafka producer"
type: application
version: 0.1.0
appVersion: "2.2.0"
dependencies:
  - name: dfe-common
    version: "0.3.0"
    repository: "file://../../library/dfe-common"
