apiVersion: v2
name: network-policies
description: Kubernetes NetworkPolicies for DFE namespace isolation
type: application
version: 0.2.1
appVersion: "1.1.0"
dependencies:
  - name: dfe-common
    version: "0.5.0"
    repository: "file://../../library/dfe-common"
