apiVersion: v2
name: dfe-transform-wasm
description: "WASM plugin execution transform — Kafka consumer → WASM → Kafka producer"
type: application
version: 0.1.1
appVersion: "2.2.0"
dependencies:
  - name: dfe-common
    version: "0.12.0"
    repository: "file://../../library/dfe-common"
