apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dfe-common.fullname" . }}
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dfe-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dfe-common.labels" . | nindent 8 }}
    spec:
      containers:
        - name: ferretdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
          env:
            - name: FERRETDB_POSTGRESQL_URL
              value: "postgres://$(PGUSER):$(PGPASSWORD)@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}?sslmode=prefer"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.secretName }}
                  key: {{ .Values.postgresql.secretUserKey }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.secretName }}
                  key: {{ .Values.postgresql.secretPasswordKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 5
            periodSeconds: 5
