{{- if and (eq .Values.kafka.provider "strimzi") (or (eq .Values.kafka.mode "single") (eq .Values.kafka.mode "cluster")) }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: {{ .Values.user.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  authentication:
    type: {{ .Values.user.authentication.type }}
  authorization:
    type: simple
    acls:
      # Allow DFE services to produce/consume on all dfe topics
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations: ["Read", "Write", "Create", "Describe"]
      - resource:
          type: group
          name: "dfe-*"
          patternType: prefix
        operations: ["Read", "Describe"]
{{- end }}
