{{- if .Values.oidc.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "dfe-common.fullname" . }}-oidc
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.oidc.clientSecretName | default (printf "%s-oidc-secret" (include "dfe-common.fullname" .)) }}
  data:
    - secretKey: client-secret
      remoteRef:
        key: dfe/vpn/oidc-client-secret
{{- end }}
