{{- if .Values.oidc.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "dfe-common.fullname" . }}-oidc
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.oidc.secretStoreName | default "dfe-secret-store" }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.oidc.clientSecretName | default (printf "%s-oidc-secret" (include "dfe-common.fullname" .)) }}
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.project }}/{{ .Values.env }}/oidc/{{ .Values.oidc.providerName | default "vpn" }}
        property: client-secret
{{- end }}
