{{- if .Values.transforms }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: dfe-kafka-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: sasl
      name: {{ .Values.kafka.authSecretName }}
      key: sasl.jaas.config
    - parameter: username
      name: {{ .Values.kafka.authSecretName }}
      key: user
    - parameter: password
      name: {{ .Values.kafka.authSecretName }}
      key: password
{{- end }}
