apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: dfe-envoy
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
