{{- if include "envoy-gateway-config.routeEnabled" (dict "ctx" . "key" "links") }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.routes.links.routeName }}
  namespace: {{ include "envoy-gateway-config.routeNs" (dict "ctx" . "key" "links") }}
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - "{{ include "envoy-gateway-config.routeHost" (dict "ctx" . "key" "links") }}.{{ .Values.domain }}"
  rules:
    - backendRefs:
        - name: {{ .Values.routes.links.backendService }}
          port: {{ .Values.routes.links.backendPort }}
          group: ""
          kind: Service
          weight: 1
{{- end }}
