{{- if .Values.routes.links.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: links
  namespace: {{ .Values.routes.links.backendNamespace | default .Release.Namespace }}
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - "{{ .Values.routes.links.hostname | default .Values.hostnames.links }}.{{ .Values.domain }}"
  rules:
    - backendRefs:
        - name: {{ .Values.routes.links.backendService }}
          port: {{ .Values.routes.links.backendPort }}
          group: ""
          kind: Service
          weight: 1
{{- end }}
