{{- if .Values.routes.gitea.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitea
  namespace: {{ .Values.routes.gitea.backendNamespace | default .Release.Namespace }}
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - "{{ .Values.routes.gitea.hostname }}.{{ .Values.domain }}"
  rules:
    - backendRefs:
        - name: {{ .Values.routes.gitea.backendService }}
          port: {{ .Values.routes.gitea.backendPort }}
{{- end }}
