{{- if .Values.toolbox.pod.kubeApiAccess }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dfe-common.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
{{- end }}
