#!/usr/bin/env bash
# preview.sh -- an isolated preview environment from BRANCH images.
#
# Builds each service from its own checkout, pushes to the registry's preview
# project (never the release registry, never main), deploys, then tears down.
#
# Usage:
#   preview.sh up   <name> [--hyperdx <branch>] [--engine <branch>] \
#                          [--infra <branch>] [--deploy <branch>] \
#                          [--services hyperdx,engine]
#   preview.sh sync <name> [--services ...]
#   preview.sh down <name>
#   preview.sh status <name>
#
# Every location is an environment variable: REGISTRY_HOST and DEPLOY_REPO_URL
# (both required), PREVIEW_PROJECT, KUBE_CONTEXT (default: the kubeconfig's
# current context), and DFE_HYPERDX_REPO / DFE_ENGINE_REPO, which default to a
# sibling checkout beside this repo.
#
# Example:
#   preview.sh up hdx29 --hyperdx chore/upstream-sync-2.29 --services hyperdx
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECKOUTS="$(dirname "$REPO_ROOT")"

# ---- config -----------------------------------------------------------------
REGISTRY_HOST="${REGISTRY_HOST:-}"                 # the preview registry (global.registry)
PREVIEW_PROJECT="${PREVIEW_PROJECT:-dfe-preview}"  # the project images are pushed to
DEPLOY_REPO_URL="${DEPLOY_REPO_URL:-}"             # the cluster secret's repo_url
INFRA_BRANCH_DEFAULT="main"
DEPLOY_BRANCH_DEFAULT="main"

# service registry: name | source repo | dockerfile (rel to repo) | image name
#   hyperdx image is built from the dfe-hyperdx FORK; its CHART lives in
#   dfe-infra/helm/charts/hyperdx. engine image from dfe-engine; chart dfe-engine.
declare -A SVC_REPO=(
  [hyperdx]="${DFE_HYPERDX_REPO:-$CHECKOUTS/dfe-hyperdx}"
  [engine]="${DFE_ENGINE_REPO:-$CHECKOUTS/dfe-engine}"
)
declare -A SVC_DOCKERFILE=(
  [hyperdx]="docker/hyperdx/Dockerfile"
  [engine]="Dockerfile"
)
# Build TARGET (multi-stage). hyperdx: `prod` = the app-only image the chart deploys
# (node alpine, serves UI + in-process api) -- NOT `all-in-one*` (bundles CH+otel).
declare -A SVC_TARGET=(
  [hyperdx]="prod"
  [engine]=""
)

die() { echo "ERROR: $*" >&2; exit 1; }
log() { echo ">> $*" >&2; }

ns_of() { echo "dfe-preview-$1"; }

# The context to act on: the caller's if set, else whatever kubectl is pointed at.
kube_context() {
  if [[ -n "${KUBE_CONTEXT:-}" ]]; then
    echo "$KUBE_CONTEXT"
    return
  fi
  kubectl config current-context 2>/dev/null \
    || die "no KUBE_CONTEXT set and no current kubeconfig context"
}

# ---- build + push one service image from a branch ---------------------------
build_push() {   # <service> <branch> <preview-name>  -> echoes the pushed tag
  local svc=$1 branch=$2 name=$3
  local repo="${SVC_REPO[$svc]:-}" dockerfile="${SVC_DOCKERFILE[$svc]:-}" target="${SVC_TARGET[$svc]:-}"
  [[ -n "$repo" ]] || die "unknown service '$svc'"
  [[ -d "$repo" ]] || die "no checkout for '$svc' at $repo -- set DFE_$(echo "$svc" | tr '[:lower:]' '[:upper:]')_REPO"
  [[ -n "$REGISTRY_HOST" ]] || die "set REGISTRY_HOST to the registry the preview images push to"
  local sha; sha=$(git -C "$repo" rev-parse --short "$branch") || die "bad branch $branch in $repo"
  local tag="${REGISTRY_HOST}/${PREVIEW_PROJECT}/${svc}:${name}-${sha}"
  log "build $svc  ${repo}@${branch} ($sha)  ->  $tag${target:+  (target: $target)}"
  docker build -t "$tag" ${target:+--target "$target"} -f "${repo}/${dockerfile}" "$repo"
  # Needs a prior `docker login "$REGISTRY_HOST"` as the preview project's robot.
  docker push "$tag"
  echo "$tag"
}

# ---- render the image-override values for the preview -----------------------
# Writes a values file that points the charts at the preview images.
write_overrides() {   # <preview-name> <svc=tag> ...
  local name=$1; shift
  local f="${REPO_ROOT}/.tmp/preview-${name}-images.yaml"
  mkdir -p "${REPO_ROOT}/.tmp"
  {
    echo "# generated by preview.sh -- image overrides for preview '${name}'"
    echo "global:"
    echo "  registry: ${REGISTRY_HOST}/${PREVIEW_PROJECT}"
    for kv in "$@"; do
      local svc="${kv%%=*}" tag="${kv#*=}"
      # hyperdx chart reads root image.* and defaults to ghcr -> override repo+tag
      if [[ "$svc" == "hyperdx" ]]; then
        echo "image:"
        echo "  repository: ${tag%:*}"
        echo "  tag: ${tag##*:}"
      fi
    done
  } > "$f"
  echo "$f"
}

# ---- deploy the preview -----------------------------------------------------
# One app per service, created imperatively: a preview is ephemeral and
# single-service, so it never enters the declarative appset set.
deploy() {   # <preview-name> <infra-branch> <deploy-branch> <overrides-file> <service...>
  local name=$1 infra=$2 deploy=$3 overrides=$4; shift 4
  local ns; ns=$(ns_of "$name")
  [[ -n "$DEPLOY_REPO_URL" ]] || die "set DEPLOY_REPO_URL to the cluster secret's repo_url"
  for svc in "$@"; do
    local chart="hyperdx"; [[ "$svc" == "engine" ]] && chart="dfe-engine"
    log "argocd app create preview-${name}-${svc}  (chart @ ${infra}, ns ${ns})"
    argocd app create "preview-${name}-${svc}" \
      --repo "$DEPLOY_REPO_URL" --revision "$infra" \
      --path "helm/charts/${chart}" \
      --dest-server https://kubernetes.default.svc --dest-namespace "$ns" \
      --values "../../../argocd/values/common.yaml" \
      --values-literal-file "$overrides" \
      --sync-policy automated --sync-option CreateNamespace=true \
      --upsert
    argocd app sync "preview-${name}-${svc}"
  done
}

# ---- subcommands ------------------------------------------------------------
cmd_up() {
  local name=$1; shift
  local infra="$INFRA_BRANCH_DEFAULT" deploy="$DEPLOY_BRANCH_DEFAULT" services="hyperdx"
  declare -A BR=()
  while [[ $# -gt 0 ]]; do case "$1" in
    --hyperdx) BR[hyperdx]="$2"; shift 2;;
    --engine)  BR[engine]="$2"; shift 2;;
    --infra)   infra="$2"; shift 2;;
    --deploy)  deploy="$2"; shift 2;;
    --services) services="$2"; shift 2;;
    *) die "unknown flag $1";;
  esac; done
  IFS=',' read -ra SVCS <<< "$services"
  local overrides_args=()
  for svc in "${SVCS[@]}"; do
    local br="${BR[$svc]:-main}"
    local tag; tag=$(build_push "$svc" "$br" "$name")
    overrides_args+=("${svc}=${tag}")
  done
  local overrides; overrides=$(write_overrides "$name" "${overrides_args[@]}")
  deploy "$name" "$infra" "$deploy" "$overrides" "${SVCS[@]}"
  log "preview '$name' up in namespace $(ns_of "$name"). Port-forward or ingress to view."
}

cmd_sync() {  # rebuild changed images + resync (fast loop)
  local name=$1; shift
  cmd_up "$name" "$@"
}

cmd_down() {
  local name=$1; local ns; ns=$(ns_of "$name")
  log "delete preview '$name' (apps + namespace $ns)"
  # BSD xargs has no -r, so the empty case is guarded here rather than by a flag.
  local apps; apps=$(argocd app list -o name 2>/dev/null | grep "^preview-${name}-" || true)
  if [[ -n "$apps" ]]; then
    echo "$apps" | xargs -n1 argocd app delete --cascade -y || true
  fi
  kubectl --context "$(kube_context)" delete ns "$ns" --ignore-not-found
  # The preview tags stay until the registry project's retention policy drops them.
}

cmd_status() {
  local name=$1; local ns; ns=$(ns_of "$name")
  argocd app list 2>/dev/null | grep "preview-${name}-" || true
  kubectl --context "$(kube_context)" -n "$ns" get pods 2>/dev/null || true
}

main() {
  local sub="${1:-}"; shift || true
  case "$sub" in
    up)     cmd_up "$@";;
    sync)   cmd_sync "$@";;
    down)   cmd_down "$@";;
    status) cmd_status "$@";;
    *) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 1;;
  esac
}
main "$@"
