#!/usr/bin/env bash
# preview.sh -- DRAFT 2026-07-07 (branch-preview cycle, Group 2).
#
# Spin an isolated preview env on devex k8s from BRANCH images, built to the
# Harbor `dfe-preview` project (never ghcr, never main). Iterate build+deploy,
# then tear down. Design + open decisions:
#   docs/plans/2026-07-08-branch-preview-cycle.md
#
# STATUS: draft for review. Marked DECIDE where an open question changes behaviour,
# and NEEDS-CRED where a Harbor robot / cluster mutation is required (morning).
#
# Usage:
#   preview.sh up   <name> [--hyperdx <branch>] [--engine <branch>] \
#                          [--infra <branch>] [--deploy <branch>] \
#                          [--services hyperdx,engine]
#   preview.sh sync <name> [--services ...]
#   preview.sh down <name>
#   preview.sh status <name>
#
# Example (HyperDX 2.29 eyeball):
#   preview.sh up hdx29 --hyperdx chore/upstream-sync-2.29 --services hyperdx
set -euo pipefail

# ---- config (DECIDE: confirm host + project in the morning) -----------------
HARBOR_HOST="${HARBOR_HOST:-inhyperi.io}"          # confirm exact global.registry
PREVIEW_PROJECT="${PREVIEW_PROJECT:-dfe-preview}"  # Harbor project (create w/ admin)
KUBE_CONTEXT="${KUBE_CONTEXT:-devex}"
INFRA_REPO="${INFRA_REPO:-/Volumes/projects/dfe-infra}"
DEPLOY_REPO_URL="git@github.com:hyperi-io/dfe-infra.git"   # from cluster-secret repo_url
INFRA_BRANCH_DEFAULT="main"
DEPLOY_BRANCH_DEFAULT="main"

# service registry: name | source repo | dockerfile (rel to repo) | image name
#   hyperdx image is built from the dfe-hyperdx FORK; its CHART lives in
#   dfe-infra/helm/charts/hyperdx. engine image from dfe-engine; chart dfe-engine.
declare -A SVC_REPO=(
  [hyperdx]="/Volumes/projects/dfe-hyperdx"
  [engine]="/Volumes/projects/dfe-engine"
)
declare -A SVC_DOCKERFILE=(
  [hyperdx]="docker/hyperdx/Dockerfile"
  [engine]="Dockerfile"
)
# Build TARGET (multi-stage). hyperdx: `prod` = the app-only image the chart deploys
# (node alpine, serves UI + in-process api) -- NOT `all-in-one*` (bundles CH+otel).
declare -A SVC_TARGET=(
  [hyperdx]="prod"
  [engine]=""
)

die() { echo "ERROR: $*" >&2; exit 1; }
log() { echo ">> $*" >&2; }

ns_of() { echo "dfe-preview-$1"; }

# ---- build + push one service image from a branch ---------------------------
build_push() {   # <service> <branch> <preview-name>  -> echoes the pushed tag
  local svc=$1 branch=$2 name=$3
  local repo="${SVC_REPO[$svc]:-}" dockerfile="${SVC_DOCKERFILE[$svc]:-}" target="${SVC_TARGET[$svc]:-}"
  [[ -n "$repo" ]] || die "unknown service '$svc'"
  local sha; sha=$(git -C "$repo" rev-parse --short "$branch") || die "bad branch $branch in $repo"
  local tag="${HARBOR_HOST}/${PREVIEW_PROJECT}/${svc}:${name}-${sha}"
  log "build $svc  ${repo}@${branch} ($sha)  ->  $tag${target:+  (target: $target)}"
  # DECIDE: build args per service (hyperdx needs none; the engine image needs the
  # hyperi PyPI index creds for `uv` -- pull from OpenBao kv/services).
  docker build -t "$tag" ${target:+--target "$target"} -f "${repo}/${dockerfile}" "$repo"
  docker push "$tag"      # NEEDS-CRED: docker login ${HARBOR_HOST} as the dfe-preview robot
  echo "$tag"
}

# ---- render the image-override values for the preview -----------------------
# Writes a values file that points the charts at the Harbor preview images.
write_overrides() {   # <preview-name> <svc=tag> ...
  local name=$1; shift
  local f="/tmp/preview-${name}-images.yaml"
  {
    echo "# generated by preview.sh -- image overrides for preview '${name}'"
    echo "global:"
    echo "  registry: ${HARBOR_HOST}/${PREVIEW_PROJECT}"
    for kv in "$@"; do
      local svc="${kv%%=*}" tag="${kv#*=}"
      # hyperdx chart hardcodes ghcr -> must override repository+tag explicitly
      if [[ "$svc" == "hyperdx" ]]; then
        echo "hyperdx:"
        echo "  image:"
        echo "    repository: ${tag%:*}"
        echo "    tag: ${tag##*:}"
      fi
    done
  } > "$f"
  echo "$f"
}

# ---- deploy the preview -----------------------------------------------------
# DECIDE (open Q2): preview ApplicationSet (argocd/appsets/preview-apps.yaml) vs
# the imperative `argocd app create` below. The imperative path is simplest for an
# ephemeral single-service preview and is what this draft uses; the appset is the
# declarative multi-service productionised form.
deploy() {   # <preview-name> <infra-branch> <deploy-branch> <overrides-file> <service...>
  local name=$1 infra=$2 deploy=$3 overrides=$4; shift 4
  local ns; ns=$(ns_of "$name")
  for svc in "$@"; do
    local chart="hyperdx"; [[ "$svc" == "engine" ]] && chart="dfe-engine"
    log "argocd app create preview-${name}-${svc}  (chart @ ${infra}, ns ${ns})"
    # NEEDS-CRED / NEEDS-OK: mutates the shared cluster. Run attended or with OK.
    argocd app create "preview-${name}-${svc}" \
      --repo "$DEPLOY_REPO_URL" --revision "$infra" \
      --path "helm/charts/${chart}" \
      --dest-server https://kubernetes.default.svc --dest-namespace "$ns" \
      --values "../../../argocd/values/common.yaml" \
      --values-literal-file "$overrides" \
      --sync-policy automated --sync-option CreateNamespace=true \
      --upsert
    argocd app sync "preview-${name}-${svc}"
  done
}

# ---- subcommands ------------------------------------------------------------
cmd_up() {
  local name=$1; shift
  local infra="$INFRA_BRANCH_DEFAULT" deploy="$DEPLOY_BRANCH_DEFAULT" services="hyperdx"
  declare -A BR=()
  while [[ $# -gt 0 ]]; do case "$1" in
    --hyperdx) BR[hyperdx]="$2"; shift 2;;
    --engine)  BR[engine]="$2"; shift 2;;
    --infra)   infra="$2"; shift 2;;
    --deploy)  deploy="$2"; shift 2;;
    --services) services="$2"; shift 2;;
    *) die "unknown flag $1";;
  esac; done
  IFS=',' read -ra SVCS <<< "$services"
  local overrides_args=()
  for svc in "${SVCS[@]}"; do
    local br="${BR[$svc]:-main}"
    local tag; tag=$(build_push "$svc" "$br" "$name")
    overrides_args+=("${svc}=${tag}")
  done
  local overrides; overrides=$(write_overrides "$name" "${overrides_args[@]}")
  deploy "$name" "$infra" "$deploy" "$overrides" "${SVCS[@]}"
  log "preview '$name' up in namespace $(ns_of "$name"). Port-forward or ingress to view."
}

cmd_sync() {  # rebuild changed images + resync (fast loop)
  local name=$1; shift
  # DECIDE: with Argo Image Updater this is just a rebuild+push; without it, resync.
  cmd_up "$name" "$@"
}

cmd_down() {
  local name=$1; local ns; ns=$(ns_of "$name")
  log "delete preview '$name' (apps + namespace $ns)"
  # NEEDS-OK: kubectl/argocd delete is on the AFK denylist -- run attended.
  argocd app list -o name 2>/dev/null | grep "^preview-${name}-" | xargs -r -n1 argocd app delete --cascade -y || true
  kubectl --context "$KUBE_CONTEXT" delete ns "$ns" --ignore-not-found
  log "TODO: optionally GC Harbor tags for '$name' (or rely on the project retention policy)"
}

cmd_status() {
  local name=$1; local ns; ns=$(ns_of "$name")
  argocd app list 2>/dev/null | grep "preview-${name}-" || true
  kubectl --context "$KUBE_CONTEXT" -n "$ns" get pods 2>/dev/null || true
}

main() {
  local sub="${1:-}"; shift || true
  case "$sub" in
    up)     cmd_up "$@";;
    sync)   cmd_sync "$@";;
    down)   cmd_down "$@";;
    status) cmd_status "$@";;
    *) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 1;;
  esac
}
main "$@"
