{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-common.fullname" . }}-config
  labels:
    {{- include "dfe-common.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
{{ include "dex.config" . | indent 4 }}
{{- end }}
