apiVersion: v2
name: envoy-gateway-config
description: GatewayClass, Gateway, and ClusterIssuer for Envoy Gateway ingress
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: dfe-common
    version: "0.7.0"
    repository: "file://../../library/dfe-common"
